### ISSUE TITLE
Is the Spaces Section Accessible?

### ISSUE THREAD

**Issue by z-t-y** [rice0208/rice#1]
# Spaces Section Can't Access
## It Shows JavaScript:Void(0)
I can't access the spaces part of your website.
Are you still looking for techs to solve this?
**Python Flask** may be the best choice and that's why I fork(copy) your project.
Here is my website:
<a href="https://andyzhou.pythonanywhere.com">LSFD 202201 Website</a>
Do you fell suprised to see me(zty) here?😀😎😃

**Comment by z-t-y** [comment]
@rice0208 I know no one else will ever go to find our conversation. I think we can chat here instead of sending email all the time and crushing our OutLook Accounts.
I am z-t-y.

**Comment by rice0208** [comment]
hahaha, yeah, I'm looking for ways to enable js, php and sql to do that, maybe as you say Python would be better

**Comment by z-t-y** [comment]
Yep. A Website made of Python is totally free,
But  A Website made of php and sql is not free(Or you can publish a free one with a STUPID AND COMPLEX IP address).
Python flask is the only way that I can get a free domain name.

**Comment by z-t-y** [comment]
Yep. A Website made of Python is totally <strong>free</strong>,
But  A Website made of php and sql is not free(Or you can publish a free one with a 
<strong>STUPID AND COMPLEX</strong> IP address).
Python flask is the only way that <strong>I</strong> can get a <strong>free</strong> domain name.

**Comment by z-t-y** [comment]
Do you notice the number of **fork** button is **1**?
That's the one I made to **'copy'** your project
